version: '3.9'
services:
  sql:
    build:
      context: ./sql  # Ruta al directorio que contiene el Dockerfile
    container_name: sql-db
    environment:
      - DB_HOST=sql
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      gateway_network:
        ipv4_address: 172.90.0.40


  nginx-router:
    build: ./nginx
    ports:
      - "8080:80"      # Puerto HTTP estándar
    networks:
      gateway_network:
        ipv4_address: 172.90.0.11
    depends_on:
      - control-frontend
      - control-backend
      - control-grpc

  gateway:
    build: ./router
    ports:
      - "5000:5000"
    cap_add:
      - NET_RAW
    networks:
      gateway_network:
        ipv4_address: 172.90.0.10


  control-frontend:
    build: ./control/frontend
    ports:
      - "3000:3000"
    networks:
      gateway_network:
        ipv4_address: 172.90.0.31
  control-backend:
    build: ./control/backend
    environment:
      DB_HOST: sql
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    networks:
      gateway_network:
        ipv4_address: 172.90.0.32
  control-grpc:
    build: ./control/grpc
    environment:
      DB_HOST: sql
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "50051:50051"
    networks:
      gateway_network:
        ipv4_address: 172.90.0.33

networks:
  gateway_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.90.0.0/24

volumes:
  pgdata:
