# Usa la imagen oficial de PostgreSQL como base
FROM docker.io/library/postgres:latest

# Configura variables de entorno (esto es opcional si ya las defines en el podman-compose.yml)
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=mydb
