version: '3.9'

services:
  sql:
    image: postgres:latest
    container_name: sql-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      gateway_my_network:
        ipv4_address: 172.90.0.40

volumes:
  pgdata:

networks:
  gateway_my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.90.0.0/24
